### PR TITLE
express but wgytcraft

### LINKED ISSUE #77: our own versions of res.send and res.json
also add res.xml

### PR DESCRIPTION
**Pull request by wgyt**
**Resolves**

Resolves #77 

**Changes**

I added res.json,  res.xml, res.send, res.sendFile, res.redirect, and res.download
**Reason for changes**

So making 1host.js modules is easy

**Tests**

it works, @GrahamSH-LLK said so
image

### CODE REVIEW

**Comment by retronbv** [comment]
i am sorry but i have ocd

**Review by thecoder876 — COMMENTED** [review]
all good

**Comment by retronbv** [comment]
> all good

It’s already merged dood

**Comment by thecoder876** [comment]
> > all good
> 
> It’s already merged dood

@retronbv ik

**Pull request merged**
