### PR TITLE
change style on remaining shields.io badges

### PR DESCRIPTION
**Pull request by thecoder876**
cc @wgyt, @GrahamSH-LLK, @retronbv

### CODE REVIEW

**Comment by wgyt** [comment]
please make the codacy badge and npm badge consistant

**Comment by thecoder876** [comment]
> please make the codacy badge and npm badge consistant

@wgyt i can't, codacy doesn't use shields.io

**Comment by wgyt** [comment]
> > please make the codacy badge and npm badge consistant
> 
> @wgyt i can't, codacy doesn't use shields.io

just use the codacy api

**Comment by thecoder876** [comment]
> > > please make the codacy badge and npm badge consistant
> > 
> > 
> > [ping removed] i can't, codacy doesn't use shields.io
> 
> just use the codacy api

@wgyt wdym (i've never used codacy before)

**Comment by wgyt** [comment]
> @wgyt wdym (i've never used codacy before)

you could get the data from the codacy api and use it in a badge

**Review by wgyt — APPROVED** [review]

**Pull request merged**
