### PR TITLE
Add issue and PR templates

### PR DESCRIPTION
**Pull request by retronbv**
Draft, pls no merge thanks

### CODE REVIEW

**Review by wgyt — CHANGES_REQUESTED** [review]
please change the issue labels @retronbv

**Comment by retronbv** [comment]
> please change the issue labels @retronbv

i just realized this is already a thing

**Comment by retronbv** [comment]
should i continue making or scrap it because it is already a thing lmao

**Comment by wgyt** [comment]
> should i continue making or scrap it because it is already a thing lmao

can you make some more templates?

**Comment by retronbv** [comment]
> > should i continue making or scrap it because it is already a thing lmao
> 
> can you make some more templates?

ig i could, what kind of templates are we talking about here?

**Comment by wgyt** [comment]
> > > should i continue making or scrap it because it is already a thing lmao
> > 
> > 
> > can you make some more templates?
> 
> ig i could, what kind of templates are we talking about here?

bug categories
dev facing
blank issue
add links to discussions for help
and Report a security vulnerability

**Comment by thecoder876** [comment]
BRUHHH i wanted to do this

**Comment by retronbv** [comment]
> BRUHHH i wanted to do this

too bad

**Comment by wgyt** [comment]
> BRUHHH i wanted to do this

You can commit to the templates branch if you want

**Review by thecoder876 — CHANGES_REQUESTED** [review]
please change "Have you tested this pull request?" into "Have you tested this pull request's changes?"

**Comment by retronbv** [comment]
> please change "Have you tested this pull request?" into "Have you tested this pull request's changes?"

the lead dev seems to disagree, so no
image

**Comment by thecoder876** [comment]
> > please change "Have you tested this pull request?" into "Have you tested this pull request's changes?"
> 
> the lead dev seems to disagree, so no
> image

@retronbv lol

**Review by wgyt — APPROVED** [review]

**Pull request merged**
